# Generated by Django 5.2.14 on 2026-05-17 22:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finsio_concept', models.CharField(help_text="e.g. 'revenue', 'accounts_receivable', 'tax_collected'", max_length=64)),
                ('ledger_account_code', models.CharField(help_text="Account code in django-ledger's ChartOfAccounts", max_length=32)),
                ('ledger_account_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_mappings', to='core.entity')),
            ],
            options={
                'ordering': ['entity', 'finsio_concept'],
                'unique_together': {('entity', 'finsio_concept')},
            },
        ),
        migrations.CreateModel(
            name='BeancountSyncRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal_entry_id', models.CharField(help_text='UUID of the django-ledger JournalEntryModel', max_length=64)),
                ('ledger_account_code', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('conflict', 'Conflict')], default='pending', max_length=16)),
                ('beancount_file', models.CharField(blank=True, default='', help_text='Path to the generated beancount file', max_length=512)),
                ('beancount_hash', models.CharField(blank=True, default='', help_text='SHA-256 of beancount content for conflict detection', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beancount_syncs', to='core.entity')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity', 'status'], name='accounting__entity__a65ef8_idx'), models.Index(fields=['journal_entry_id'], name='accounting__journal_1c30cf_idx')],
            },
        ),
    ]
