# Generated by Django 5.2.14 on 2026-05-17 22:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('prepared', 'Prepared'), ('in_progress', 'In Progress'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='new', max_length=20)),
                ('processor', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('braintree', 'Braintree'), ('authorize_net', 'Authorize.Net')], db_index=True, max_length=30, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('SEK', 'Swedish Krona'), ('NOK', 'Norwegian Krone'), ('DKK', 'Danish Krone'), ('NZD', 'New Zealand Dollar')], default='USD', max_length=3)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Payment ID at the provider (e.g. Stripe pi_xxx)', max_length=255, null=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('customer_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('redirect_url', models.URLField(blank=True, help_text='URL to redirect customer to complete payment', null=True)),
                ('callback_url', models.URLField(blank=True, help_text='URL to notify after payment completion', null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='invoicing.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('prepared', 'Prepared'), ('status_changed', 'Status Changed'), ('provider_event', 'Provider Event'), ('webhook_received', 'Webhook Received'), ('refund', 'Refund')], max_length=30)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('provider_event_id', models.CharField(blank=True, db_index=True, help_text='Provider event ID for idempotent processing', max_length=255, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='finsio_payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(db_index=True, max_length=255)),
                ('provider', models.CharField(choices=[('stripe_card', 'Stripe Card'), ('stripe_sepa', 'Stripe SEPA Debit'), ('stripe_ach', 'Stripe ACH Direct Debit'), ('paypal_billing', 'PayPal Billing Agreement'), ('braintree_card', 'Braintree Card')], max_length=30)),
                ('external_token', models.CharField(help_text="Provider's payment method token", max_length=255)),
                ('display_name', models.CharField(blank=True, help_text='Human-readable name (e.g. Visa ending 4242)', max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='finsio_paym_status_325ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['processor', 'external_id'], name='finsio_paym_process_61dec5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer_id', 'status'], name='finsio_paym_custome_30b9dc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['payment', 'event_type', 'created_at'], name='finsio_paym_payment_d4123d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('customer_id', 'provider', 'external_token')},
        ),
    ]
